### PR TITLE
Add exportable custom plain logger

### PR DESCRIPTION
**Pull request by cyrnicolase**
#1169

### CODE REVIEW

**Comment by cyrnicolase** [comment]
图片

What's wrong ?

**Comment by suchen-sci** [comment]
image
@cyrnicolase

**Comment by cyrnicolase** [comment]
It's so sad!

**Comment by xxx7xxxx** [comment]
For creating and manipulating OS-specific paths directly use [os.PathSeparator](http://golang.org/pkg/os) and the [path/filepath](http://golang.org/pkg/path/filepath/) package.

**Comment by cyrnicolase** [comment]
@suchen-sci @xxx7xxxx Could you please review the code for me?

**Review by xxx7xxxx — APPROVED** [review]

**Pull request merged**
